/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.knowledgeconquest;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author Spychacz
 */
public class KnowledgeConquest extends javax.swing.JFrame {

    /**
     * Creates new form KnowledgeConquest
     */
    public KnowledgeConquest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        txtField_p1 = new javax.swing.JTextField();
        txtField_p2 = new javax.swing.JTextField();
        txtField_p4 = new javax.swing.JTextField();
        txtField_p3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        gamePanel = new javax.swing.JPanel();
        boardPanel = new javax.swing.JPanel();
        scoreboardPanel = new javax.swing.JPanel();
        p4Label = new javax.swing.JLabel();
        p1Label = new javax.swing.JLabel();
        p2Label = new javax.swing.JLabel();
        p3Label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Knowledge Conquest");
        setPreferredSize(new java.awt.Dimension(1280, 1024));
        setResizable(false);

        cardPanel.setPreferredSize(new java.awt.Dimension(1280, 1024));
        cardPanel.setLayout(new java.awt.CardLayout());

        menuPanel.setForeground(new java.awt.Color(204, 0, 0));
        menuPanel.setPreferredSize(new java.awt.Dimension(1280, 1024));

        txtField_p1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtField_p1.setForeground(new java.awt.Color(204, 204, 204));
        txtField_p1.setText("First player");
        txtField_p1.setToolTipText("");
        txtField_p1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtField_p1.setName("fptxt"); // NOI18N
        txtField_p1.setNextFocusableComponent(startBtn);
        txtField_p1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtField_p1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtField_p1FocusLost(evt);
            }
        });
        txtField_p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_p1ActionPerformed(evt);
            }
        });

        txtField_p2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtField_p2.setForeground(new java.awt.Color(204, 204, 204));
        txtField_p2.setText("Second player");
        txtField_p2.setToolTipText("");
        txtField_p2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtField_p2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtField_p2FocusLost(evt);
            }
        });
        txtField_p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_p2ActionPerformed(evt);
            }
        });

        txtField_p4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtField_p4.setForeground(new java.awt.Color(204, 204, 204));
        txtField_p4.setText("Fourth player");
        txtField_p4.setToolTipText("");
        txtField_p4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtField_p4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtField_p4FocusLost(evt);
            }
        });
        txtField_p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_p4ActionPerformed(evt);
            }
        });

        txtField_p3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtField_p3.setForeground(new java.awt.Color(204, 204, 204));
        txtField_p3.setText("Third player");
        txtField_p3.setToolTipText("");
        txtField_p3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtField_p3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtField_p3FocusLost(evt);
            }
        });
        txtField_p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_p3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Knowledge Conquest!");

        startBtn.setText("Start game");
        startBtn.setName("startBtn"); // NOI18N
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(462, 462, 462)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtField_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtField_p3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtField_p4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtField_p2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(483, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField_p4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField_p3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(665, Short.MAX_VALUE))
        );

        txtField_p1.getAccessibleContext().setAccessibleName("firstPtxtField");

        cardPanel.add(menuPanel, "menuCard");
        menuPanel.getAccessibleContext().setAccessibleName("");
        menuPanel.getAccessibleContext().setAccessibleDescription("");

        gamePanel.setName("gamePanel"); // NOI18N
        gamePanel.setPreferredSize(new java.awt.Dimension(1280, 1024));

        boardPanel.setLayout(new java.awt.GridLayout(10, 10));

        scoreboardPanel.setBackground(new java.awt.Color(51, 51, 255));
        scoreboardPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        p4Label.setBackground(new java.awt.Color(204, 204, 255));
        p4Label.setOpaque(true);

        p1Label.setBackground(new java.awt.Color(255, 204, 204));
        p1Label.setOpaque(true);

        p2Label.setBackground(new java.awt.Color(153, 153, 153));
        p2Label.setOpaque(true);

        p3Label.setBackground(new java.awt.Color(153, 255, 153));
        p3Label.setOpaque(true);

        jButton1.setText("Roll");
        jButton1.setBorder(null);

        javax.swing.GroupLayout scoreboardPanelLayout = new javax.swing.GroupLayout(scoreboardPanel);
        scoreboardPanel.setLayout(scoreboardPanelLayout);
        scoreboardPanelLayout.setHorizontalGroup(
            scoreboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoreboardPanelLayout.createSequentialGroup()
                .addComponent(p1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scoreboardPanelLayout.setVerticalGroup(
            scoreboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoreboardPanelLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(scoreboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        p4Label.getAccessibleContext().setAccessibleName("p4label");
        p1Label.getAccessibleContext().setAccessibleName("p1Label");
        p2Label.getAccessibleContext().setAccessibleName("p2Label");
        p3Label.getAccessibleContext().setAccessibleName("p3Label");

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scoreboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scoreboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardPanel.add(gamePanel, "gameCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtField_p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_p2ActionPerformed

    private void txtField_p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_p4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_p4ActionPerformed

    private void txtField_p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_p3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_p3ActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
        nrOfPlayers();
        ((CardLayout)cardPanel.getLayout()).show(cardPanel, "gameCard");
        
    }//GEN-LAST:event_startBtnActionPerformed
    
    
    
    // placeholders functions
    private void txtField_p2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_p2FocusGained
        deletePlaceholder(txtField_p2, "Second player");
    }//GEN-LAST:event_txtField_p2FocusGained

    private void txtField_p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField_p1ActionPerformed

    private void txtField_p2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_p2FocusLost
        setPlaceholder(txtField_p2, "Second player");
    }//GEN-LAST:event_txtField_p2FocusLost

    private void txtField_p1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_p1FocusGained
        deletePlaceholder(txtField_p1, "First player");
    }//GEN-LAST:event_txtField_p1FocusGained

    private void txtField_p1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_p1FocusLost
        setPlaceholder(txtField_p1, "First player");
    }//GEN-LAST:event_txtField_p1FocusLost

    private void txtField_p3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_p3FocusLost
        setPlaceholder(txtField_p3, "Third player");
    }//GEN-LAST:event_txtField_p3FocusLost

    private void txtField_p3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_p3FocusGained
        deletePlaceholder(txtField_p3, "Third player");
    }//GEN-LAST:event_txtField_p3FocusGained

    private void txtField_p4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_p4FocusGained
        deletePlaceholder(txtField_p4, "Fourth player");
    }//GEN-LAST:event_txtField_p4FocusGained

    private void txtField_p4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtField_p4FocusLost
        setPlaceholder(txtField_p4, "Fourth player");
    }//GEN-LAST:event_txtField_p4FocusLost

    
    private void deletePlaceholder(JTextField jtxt, String placeholder){
        if(jtxt.getText().equals(placeholder) || jtxt.getText().isBlank()){
            jtxt.setText("");
            jtxt.setForeground(Color.black);
        }
    }
    private void setPlaceholder(JTextField jtxt, String placeholder){
        if(jtxt.getText().isBlank()){
            jtxt.setForeground(new Color(204,204,204));
            jtxt.setText(placeholder);
        }
        
    }
    private int nrOfPlayers(){
        int n=0;
        if(txtField_p1.getForeground().equals(Color.BLACK)){
            p1Label.setText(txtField_p1.getText());
            n++;
        }
        if(txtField_p2.getForeground().equals(Color.BLACK)){
            p2Label.setText(txtField_p2.getText());
            n++;
        }
        if(txtField_p3.getForeground().equals(Color.BLACK)){
            p3Label.setText(txtField_p3.getText());
            n++;
        }
        if(txtField_p4.getForeground().equals(Color.BLACK)){
            p4Label.setText(txtField_p4.getText());
            n++;
        }
        System.out.println(n);
        return n;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KnowledgeConquest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KnowledgeConquest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KnowledgeConquest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KnowledgeConquest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KnowledgeConquest().setVisible(true);
                
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardPanel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel p1Label;
    private javax.swing.JLabel p2Label;
    private javax.swing.JLabel p3Label;
    private javax.swing.JLabel p4Label;
    private javax.swing.JPanel scoreboardPanel;
    private javax.swing.JButton startBtn;
    private javax.swing.JTextField txtField_p1;
    private javax.swing.JTextField txtField_p2;
    private javax.swing.JTextField txtField_p3;
    private javax.swing.JTextField txtField_p4;
    // End of variables declaration//GEN-END:variables
}
